-- Club50 evaluator/storage migration
-- Run this in Supabase SQL Editor for project juwcvijbzjdhbiavofhd.
-- It is intentionally idempotent so it can be re-run safely.

begin;

alter table public.problems
  add column if not exists time_limit integer not null default 1,
  add column if not exists memory_limit integer not null default 256;

create table if not exists public.problem_templates (
  id integer generated by default as identity primary key,
  problem_id integer not null references public.problems(id) on delete cascade,
  language text not null,
  starter_code text,
  solution_code text,
  created_at timestamptz not null default now()
);

create table if not exists public.problem_schemas (
  id integer generated by default as identity primary key,
  problem_id integer not null references public.problems(id) on delete cascade,
  language text not null,
  schema_data jsonb not null default '{"tests":[]}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.submissions
  add column if not exists evaluation_report jsonb,
  add column if not exists compile_error text,
  add column if not exists runtime_error text,
  add column if not exists time_complexity text,
  add column if not exists space_complexity text,
  add column if not exists code_issues jsonb,
  add column if not exists optimization_suggestions jsonb,
  add column if not exists public_test_passed integer not null default 0,
  add column if not exists public_test_total integer not null default 0,
  add column if not exists hidden_test_passed integer not null default 0,
  add column if not exists hidden_test_total integer not null default 0,
  add column if not exists memory_mb integer,
  add column if not exists submitted_at timestamptz,
  add column if not exists completed_at timestamptz;

create index if not exists idx_problem_templates_problem_language
  on public.problem_templates(problem_id, language);

create index if not exists idx_problem_schemas_problem_language
  on public.problem_schemas(problem_id, language);

create index if not exists idx_submissions_problem_id
  on public.submissions(problem_id);

create index if not exists idx_submissions_user_id
  on public.submissions(user_id);

create index if not exists idx_submissions_created_at
  on public.submissions(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_problem_schemas_updated_at on public.problem_schemas;
create trigger trg_problem_schemas_updated_at
before update on public.problem_schemas
for each row
execute function public.set_updated_at();

-- Keep table-level security enabled. The backend uses the service role for
-- writes and private reads, so hidden test cases do not need public Data API access.
alter table public.problems enable row level security;
alter table public.problem_templates enable row level security;
alter table public.problem_schemas enable row level security;
alter table public.submissions enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'problems'
      and policyname = 'Public can read active problems'
  ) then
    create policy "Public can read active problems"
      on public.problems
      for select
      to anon, authenticated
      using (coalesce(is_active, true) = true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'problem_templates'
      and policyname = 'Public can read problem templates'
  ) then
    create policy "Public can read problem templates"
      on public.problem_templates
      for select
      to anon, authenticated
      using (language in ('c', 'java'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'submissions'
      and policyname = 'Authenticated can read own submissions'
  ) then
    create policy "Authenticated can read own submissions"
      on public.submissions
      for select
      to authenticated
      using (auth.uid()::text = user_id::text);
  end if;
end $$;

grant usage on schema public to anon, authenticated;
grant select on public.problems to anon, authenticated;
grant select on public.problem_templates to anon, authenticated;
grant select on public.submissions to authenticated;

-- Do not grant anon/authenticated access to problem_schemas. It contains hidden tests.
revoke all on public.problem_schemas from anon, authenticated;

commit;

-- Smoke checks
select column_name, data_type
from information_schema.columns
where table_schema = 'public'
  and table_name in ('problems', 'submissions', 'problem_templates', 'problem_schemas')
  and column_name in (
    'time_limit', 'memory_limit', 'evaluation_report', 'compile_error',
    'runtime_error', 'time_complexity', 'space_complexity', 'code_issues',
    'optimization_suggestions', 'public_test_passed', 'public_test_total',
    'hidden_test_passed', 'hidden_test_total', 'memory_mb', 'submitted_at',
    'completed_at', 'schema_data', 'starter_code'
  )
order by table_name, column_name;
